### ISSUE TITLE
Hostname check bypass

### ISSUE THREAD

**Issue by b0-n0-b0** [riad-azz/flask-allowedhosts#4]
the library fails to enforce the check due to its reliance on the `socket.gethostbyaddr` function.

The library essentially performs a `reverse DNS query` to retrieve the host associated with the `IP` in the incoming request and uses the result to determine whether access to the requested resource should be granted.

Many VPS providers allow extensive alteration of reverse DNS query content (Vultr i.e. allows to change the rDNS response body to anything, even localhost)

A malicious user can easily alter the content of the reverse DNS query response, allowing them to bypass the check and access resources they should not be able to.

**Comment by b0-n0-b0** [comment]
My suggestion, if you want to keep the DNS approach in order to be able to use hostnames and not IPs, is to perform also a DNS query on the retrieved hostname and check that at least one of the DNS provided IPs matches the request one.
This should be a safer approach

**Comment by riad-azz** [comment]
thanks for pointing out the issue with the reverse DNS check and how it can be bypassed. I will give your suggested approach a try  and see how it works. I really appreciate your input, and apologies for the Twitter situation as I am not very good with social media in general

**Comment by b0-n0-b0** [comment]
Don't worry, I'm glad I could help. Have a great day, and feel free to reach out if you want to discuss more, either here on GitHub or on Twitter `@b0n0b0__`

**Comment by riad-azz** [comment]
Hello once again! I have made the changes as you suggested to check if the request IP matches at least one of the allowed hosts IPs. Also I have updated the whole package to act as a flask extension instead of having just a decorator.

PyPI does not allow renaming packages, so I decided to delete the old project and create a new one called `flask-allowed-hosts`, which fully deprecates/discontinues the previous version. The old code wasn't behaving exactly as intended anyway, so I believe this is for the best. 

Please check the latest version and let me know if it adequately addresses the vulnerability. 
Once again, thank you for reaching out!

**Comment by b0-n0-b0** [comment]
looks good to me!
Thank you for addressing the problem and fixing it this fast

**Comment by riad-azz** [comment]
That's great! and thank you for your feedback!
